'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{EventEmitter}=require('node:events');
const {LocalAIRuntime,verifyRuntime,RELEASE}=require('../src/main/ai-runtime');
function directory(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'scribble-ai-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
async function server(t){const s=http.createServer((req,res)=>{assert.equal(req.url,'/api/version');res.setHeader('content-type','application/json');res.end(JSON.stringify({version:'0.40.0'}));});await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>s.close());return{server:s,fetcher:url=>fetch(url.replace('127.0.0.1:11434','127.0.0.1:'+s.address().port))};}
test('healthy external Ollama is reused without spawning or changing its configuration',async t=>{const external=await server(t);let spawns=0;const runtime=new LocalAIRuntime({fetcher:external.fetcher,spawnProcess:()=>{spawns++;throw Error('Must not spawn');}});const result=await runtime.ensure({endpoint:'http://127.0.0.1:11434',dataDir:directory(t)});assert.equal(result.owned,false);assert.equal(result.reused,true);assert.equal(spawns,0);runtime.close();assert.equal((await external.fetcher('http://127.0.0.1:11434/api/version')).status,200);});
test('owned server binds chosen loopback with cloud disabled and private models; concurrent starts coalesce',async t=>{const service=await server(t);let launched=false,spawns=0,configuration;const child=new EventEmitter();child.exitCode=null;child.kill=signal=>{child.signal=signal;child.exitCode=0;child.emit('exit',0);};const dir=directory(t);const runtime=new LocalAIRuntime({fetcher:url=>launched?service.fetcher(url):Promise.reject(Error('offline')),verify:async()=>'/verified/ollama',spawnProcess:(bin,args,options)=>{spawns++;configuration={bin,args,options};launched=true;return child;}});const options={endpoint:'http://127.0.0.1:11434',dataDir:dir,resourcesPath:'/resources'};const [one,two]=await Promise.all([runtime.ensure(options),runtime.ensure(options)]);assert.equal(spawns,1);assert.equal(one.owned,true);assert.deepEqual(one,two);assert.equal(configuration.options.env.OLLAMA_HOST,'127.0.0.1:11434');assert.equal(configuration.options.env.OLLAMA_NO_CLOUD,'1');assert.equal(configuration.options.env.OLLAMA_MODELS,path.join(dir,'local-ai/models'));assert.equal(configuration.options.detached,false);assert.equal(fs.statSync(configuration.options.env.OLLAMA_MODELS).mode&0o777,0o700);assert.deepEqual(configuration.args,['serve']);runtime.close();assert.equal(child.signal,'SIGTERM');});
test('runtime startup errors and timeouts do not claim readiness or leave owned process running',async t=>{for(const fail of [true,false]){const child=new EventEmitter();child.exitCode=null;child.kills=0;child.kill=()=>{child.kills++;child.exitCode=0;child.emit('exit',0);};const runtime=new LocalAIRuntime({fetcher:async()=>{throw Error('offline');},verify:async()=>'/verified/ollama',spawnProcess:()=>{if(fail)process.nextTick(()=>child.emit('error',Error('launch failed')));return child;},startupTimeout:20,wait:()=>new Promise(r=>setTimeout(r,1))});await assert.rejects(runtime.ensure({endpoint:'http://127.0.0.1:11434',dataDir:directory(t)}),fail?/launch failed/:/did not become ready/);assert.equal(child.kills,1);assert.equal(runtime.child,null);runtime.close();}});
test('managed launch refuses remote/custom endpoints',()=>{const runtime=new LocalAIRuntime();for(const endpoint of ['https://example.com','http://0.0.0.0:11434','http://127.0.0.1:12000','http://localhost:11434','http://127.0.0.1:11434/path'])assert.throws(()=>runtime.ensure({endpoint}),/only at/);runtime.close();});
test('verified package manifest detects changed executable bytes',async t=>{const dir=directory(t),file=path.join(dir,'ollama'),bytes='#!/bin/sh\nexit 0\n';fs.writeFileSync(file,bytes,{mode:0o700});fs.writeFileSync(path.join(dir,'scribble-runtime.json'),JSON.stringify({version:RELEASE.version,archiveSHA256:RELEASE.sha256,files:[{path:'ollama',sha256:crypto.createHash('sha256').update(bytes).digest('hex')}]}));assert.equal(await verifyRuntime(dir),file);fs.appendFileSync(file,'# changed');await assert.rejects(verifyRuntime(dir),/verification failed/);});
test('launcher and official bundler use the setup script exact release pin',async()=>{const {release}=await import('../scripts/setup-ai.mjs');assert.equal(RELEASE.version,release.version);assert.equal(RELEASE.sha256,release.sha256);});
