'use strict';
const test = require('node:test'), assert = require('node:assert/strict'), http = require('node:http'), fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const cli = require('../scripts/scribble.cjs');
test('CLI socket follows explicit app data directory', () => { assert.equal(cli.socketPath({ SCRIBBLE_DATA_DIR: '/tmp/custom' }), '/tmp/custom/scribble.sock'); assert.equal(cli.parseArgs(['status', '--json']).json, true); });
test('history search finds original text and error', async () => { const state = { history: [{ id: 'one', text: 'polished', original: 'spoken raw' }, { id: 'two', error: 'model unavailable' }] }; const send = async action => { assert.equal(action, 'state'); return state; }; assert.equal((await cli.execute('search', ['RAW'], send))[0].id, 'one'); assert.equal((await cli.execute('history', ['unavailable'], send))[0].id, 'two'); });
test('settings JSON object validated before dispatch', async () => { await assert.rejects(cli.execute('settings', ['[]']), /JSON object/); let dispatched; await cli.execute('settings', ['{"theme":"dark"}'], async (action, args) => { dispatched = { action, args }; return { settings: args }; }); assert.deepEqual(dispatched, { action: 'preferences', args: { theme: 'dark' } }); });
test('MCP initialize/tool listing works without app', async () => { const initialized = await cli.rpc({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18' } }); assert.equal(initialized.result.protocolVersion, '2025-06-18'); const listed = await cli.rpc({ jsonrpc: '2.0', id: 2, method: 'tools/list' }); assert.equal(listed.result.tools.length, 10); assert.ok(listed.result.tools.every(t => t.inputSchema.additionalProperties === false)); assert.equal(await cli.rpc({ jsonrpc: '2.0', method: 'notifications/initialized' }), null); });
test('MCP reports schema/engine failures as tool errors, never fake success', async () => { const message = { jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'scribble_command', arguments: { text: 123 } } }; assert.equal((await cli.rpc(message)).result.isError, true); message.params.arguments.text = 'do something'; const result = await cli.rpc(message, async () => { throw Error('Local engine is not installed'); }); assert.equal(result.result.isError, true); assert.match(result.result.content[0].text, /not installed/); assert.throws(() => cli.validateTool('scribble_record', { mode: 'arbitrary' }), /Invalid/); });
test('Unix transport sends server protocol and propagates server errors', async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'scribble-cli-')); const socketPath = path.join(dir, 'test.sock');
  const server = http.createServer((req, res) => { let body = ''; req.on('data', chunk => body += chunk); req.on('end', () => { const data = JSON.parse(body); res.end(JSON.stringify(data.action === 'models' ? { ok: true, value: ['base'] } : { ok: false, error: 'Real engine failure' })); }); });
  await new Promise(resolve => server.listen(socketPath, resolve));
  try { assert.deepEqual(await cli.request('models', {}, { socketPath }), ['base']); await assert.rejects(cli.request('transcribe-file', { file: '/tmp/audio.wav' }, { socketPath }), /Real engine failure/); }
  finally { await new Promise(resolve => server.close(resolve)); fs.rmSync(dir, { recursive: true, force: true }); }
});
test('transcribe checks file and routes note intent', async () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'scribble-cli-file-')); const file = path.join(dir, 'audio.wav'); fs.writeFileSync(file, 'test'); try { let called; await cli.execute('transcribe', [file, '--note'], async (action, args) => called = { action, args }); assert.deepEqual(called, { action: 'transcribe-file', args: { file, kind: 'note' } }); } finally { fs.rmSync(dir, { recursive: true, force: true }); } });
