'use strict';
const test = require('node:test'), assert = require('node:assert/strict'), http = require('node:http'), fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const cli = require('../scripts/scribble.cjs');
test('CLI socket follows explicit app data directory', () => { assert.equal(cli.socketPath({ SCRIBBLE_DATA_DIR: '/tmp/custom' }), '/tmp/custom/scribble.sock'); assert.equal(cli.parseArgs(['status', '--json']).json, true); });
test('history search finds original text and error', async () => { const state = { history: [{ id: 'one', text: 'polished', original: 'spoken raw' }, { id: 'two', error: 'model unavailable' }] }; const send = async action => { assert.equal(action, 'state'); return state; }; assert.equal((await cli.execute('search', ['RAW'], send))[0].id, 'one'); assert.equal((await cli.execute('history', ['unavailable'], send))[0].id, 'two'); });
test('settings JSON object validated before dispatch', async () => { await assert.rejects(cli.execute('settings', ['[]']), /JSON object/); let dispatched; await cli.execute('settings', ['{"theme":"dark"}'], async (action, args) => { dispatched = { action, args }; return { settings: args }; }); assert.deepEqual(dispatched, { action: 'preferences', args: { theme: 'dark' } }); });
test('MCP initialize/tool listing works without app', async () => { const initialized = await cli.rpc({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18' } }); assert.equal(initialized.result.protocolVersion, '2025-06-18'); const listed = await cli.rpc({ jsonrpc: '2.0', id: 2, method: 'tools/list' }); assert.equal(listed.result.tools.length, 17); assert.ok(listed.result.tools.every(t => t.inputSchema.additionalProperties === false)); assert.equal(await cli.rpc({ jsonrpc: '2.0', method: 'notifications/initialized' }), null); });
test('MCP reports schema/engine failures as tool errors, never fake success', async () => { const message = { jsonrpc: '2.0', id: 1, method: 'tools/call', params: { name: 'scribble_command', arguments: { text: 123 } } }; assert.equal((await cli.rpc(message)).result.isError, true); message.params.arguments.text = 'do something'; const result = await cli.rpc(message, async () => { throw Error('Local engine is not installed'); }); assert.equal(result.result.isError, true); assert.match(result.result.content[0].text, /not installed/); assert.throws(() => cli.validateTool('scribble_record', { mode: 'arbitrary' }), /Invalid/); });
test('Unix transport sends server protocol and propagates server errors', async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'scribble-cli-')); const socketPath = path.join(dir, 'test.sock');
  const server = http.createServer((req, res) => { let body = ''; req.on('data', chunk => body += chunk); req.on('end', () => { const data = JSON.parse(body); res.end(JSON.stringify(data.action === 'models' ? { ok: true, value: ['base'] } : { ok: false, error: 'Real engine failure' })); }); });
  await new Promise(resolve => server.listen(socketPath, resolve));
  try { assert.deepEqual(await cli.request('models', {}, { socketPath }), ['base']); await assert.rejects(cli.request('transcribe-file', { file: '/tmp/audio.wav' }, { socketPath }), /Real engine failure/); }
  finally { await new Promise(resolve => server.close(resolve)); fs.rmSync(dir, { recursive: true, force: true }); }
});
test('transcribe checks file and routes note intent', async () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'scribble-cli-file-')); const file = path.join(dir, 'audio.wav'); fs.writeFileSync(file, 'test'); try { let called; await cli.execute('transcribe', [file, '--note'], async (action, args) => called = { action, args }); assert.deepEqual(called, { action: 'transcribe-file', args: { file, kind: 'note' } }); } finally { fs.rmSync(dir, { recursive: true, force: true }); } });
test('recording stop/cancel and paste-last route explicit lifecycle actions',async()=>{const calls=[],send=async(action,args)=>{calls.push({action,args});return{dispatched:true};};await cli.execute('record',['start','note'],send);await cli.execute('record',['stop'],send);await cli.execute('record',['cancel'],send);await cli.execute('paste-last',[],send);assert.deepEqual(calls.map(x=>x.action),['start-recording','stop-recording','cancel-recording','paste-last']);assert.equal(calls[0].args.mode,'note');});
test('history filtering searches command revisions and preserves originals',async()=>{const rows=[{id:'a',kind:'command',createdAt:'2026-10-07T12:00:00Z',text:'Latest',original:'raw',revisions:[{text:'Earlier result',instruction:'Polish'}]},{id:'b',kind:'dictation',createdAt:'2026-10-06T12:00:00Z',text:'Earlier result'}];const send=async()=>({history:rows});assert.deepEqual((await cli.execute('history',['Polish','--kind','command','--since','2026-10-07T00:00:00Z','--limit','1'],send)).map(x=>x.id),['a']);assert.equal(await cli.execute('history',['original','a'],send),'raw');assert.equal((await cli.execute('history',['revisions','a'],send))[0].text,'Earlier result');await assert.rejects(cli.execute('history',['--since','not-a-date'],send),/timestamp/);});
test('copy uses selected revision and rejects conflicting selectors before clipboard action',async()=>{const calls=[],send=async(action,args)=>{calls.push({action,args});return action==='state'?{history:[{id:'a',original:'Spoken',text:'Newest',revisions:[{text:'Earlier'}]}]}:true;};await cli.execute('history',['copy','a','--revision','0'],send);assert.deepEqual(calls.at(-1),{action:'copy',args:{text:'Earlier'}});const count=calls.filter(x=>x.action==='copy').length;await assert.rejects(cli.execute('history',['copy','a','--original','--revision','0'],send),/not both/);assert.equal(calls.filter(x=>x.action==='copy').length,count);});
test('model management selects known catalog id and propagates download/cancel/delete errors',async()=>{const calls=[],send=async(action,args)=>{calls.push({action,args});if(action==='models')return[{id:'base.en'}];if(action==='preferences')return{settings:args};if(action==='delete-model')throw Error('Model is in use');return true;};await cli.execute('models',['select','base.en'],send);await cli.execute('models',['download','base.en'],send);await cli.execute('models',['cancel','base.en'],send);await assert.rejects(cli.execute('models',['delete','base.en'],send),/in use/);await assert.rejects(cli.execute('models',['select','unknown'],send),/not found/);assert.equal(calls.filter(x=>x.action==='preferences').length,1);assert.deepEqual(calls.find(x=>x.action==='preferences').args,{modelId:'base.en',speechProvider:'local'});assert.ok(calls.some(x=>x.action==='download-model'));assert.ok(calls.some(x=>x.action==='cancel-download'));});
test('settings keys preserve JSON types and memory status excludes reference content',async()=>{const calls=[],send=async(action,args)=>{calls.push({action,args});return action==='state'?{settings:{autoEnter:false},memory:[{id:'m',name:'Project',content:'Private reference',status:'indexed',enabled:true}]}:{settings:args};};await cli.execute('settings',['set','autoEnter','true'],send);assert.equal(calls.at(-1).args.autoEnter,true);assert.equal(await cli.execute('settings',['get','autoEnter'],send),false);await assert.rejects(cli.execute('settings',['get','__proto__'],send),/Unknown preference/);const status=await cli.execute('memory',['status'],send);assert.equal(status[0].status,'indexed');assert.equal(status[0].content,undefined);await cli.execute('memory',['reindex','m'],send);assert.equal(calls.at(-1).action,'memory-reindex');await cli.execute('tones',['pin','tone-one'],send);assert.deepEqual(calls.at(-1),{action:'select-tone',args:{id:'tone-one'}});await cli.execute('tones',['auto'],send);assert.equal(calls.at(-1).args.id,'');});
test('new MCP tools expose schema errors and genuine socket action failures',async()=>{const call=(name,args,send)=>cli.rpc({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}},send);const failure=await call('scribble_model_manage',{action:'download',id:'base.en'},async()=>{throw Error('CLI action unavailable');});assert.equal(failure.result.isError,true);assert.match(failure.result.content[0].text,/unavailable/);const missing=await call('scribble_history_entry',{action:'copy'},async()=>{throw Error('Should not dispatch');});assert.equal(missing.result.isError,true);assert.match(missing.result.content[0].text,/required/);const reads=await call('scribble_history_filter',{query:'prior'},async()=>({history:[{id:'a',revisions:[{text:'Prior'}]}]}));assert.equal(reads.result.isError,false);assert.equal(JSON.parse(reads.result.content[0].text)[0].id,'a');});
test('MCP stdio frames notifications and errors without contaminating stdout',async()=>{const {PassThrough}=require('node:stream'),input=new PassThrough(),output=new PassThrough();let text='';output.on('data',b=>text+=b);const lines=cli.startMCP(input,output,async()=>({history:[]}));input.write('{invalid}\n');input.write(JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'})+'\n');input.write(JSON.stringify({jsonrpc:'2.0',id:'list',method:'tools/list'})+'\n');await new Promise(r=>setTimeout(r,10));const replies=text.trim().split('\n').map(x=>JSON.parse(x));assert.equal(replies.length,2);assert.equal(replies[0].error.code,-32700);assert.equal(replies[1].id,'list');assert.equal(replies[1].result.tools.length,17);lines.close();input.end();output.end();});
test('CLI subprocess sends new lifecycle commands through an isolated private app socket',async()=>{const {execFile}=require('node:child_process'),{promisify}=require('node:util'),exec=promisify(execFile),dir=fs.mkdtempSync(path.join(os.tmpdir(),'scribble-cli-e2e-')),socket=path.join(dir,'scribble.sock'),calls=[];const server=http.createServer((req,res)=>{let body='';req.on('data',b=>body+=b);req.on('end',()=>{const value=JSON.parse(body);calls.push(value);res.end(JSON.stringify({ok:true,value:{requested:true}}));});});await new Promise(r=>server.listen(socket,r));fs.chmodSync(socket,0o600);try{for(const args of [['record','stop'],['models','cancel','base.en'],['memory','reindex','memory-one'],['tones','auto']]){const result=await exec(process.execPath,[path.resolve(__dirname,'../scripts/scribble.cjs'),...args,'--json'],{env:{...process.env,SCRIBBLE_DATA_DIR:dir}});assert.deepEqual(JSON.parse(result.stdout),args[0]==='tones'?{automatic:true}:{requested:true});assert.equal(result.stderr,'');}assert.deepEqual(calls.map(x=>x.action),['stop-recording','cancel-download','memory-reindex','select-tone']);assert.equal(calls[1].args.id,'base.en');assert.equal(fs.statSync(socket).mode&0o777,0o600);}finally{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}});
test('Unix transport never accepts HTTP error status as successful payload',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'scribble-cli-http-')),socket=path.join(dir,'test.sock');const server=http.createServer((req,res)=>{req.resume();res.writeHead(503);res.end(JSON.stringify({ok:true,value:'misleading'}));});await new Promise(r=>server.listen(socket,r));try{await assert.rejects(cli.request('state',{}, {socketPath:socket}),/503/);}finally{await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}});
