'use strict';
const { test } = require('node:test'); const assert = require('node:assert/strict');
const http = require('node:http'); const fs = require('node:fs/promises'); const os = require('node:os'); const path = require('node:path');
const { transcribe, normalize, endpoint } = require('../src/main/cloud-speech');
async function fixture(t, handler) { const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'scribble-cloud-')); const filePath = path.join(dir, 'audio.wav'); await fs.writeFile(filePath, Buffer.from('RIFFfixture')); const server = http.createServer(async (req, res) => { const chunks = []; for await (const chunk of req) chunks.push(chunk); handler(req, Buffer.concat(chunks), res); }); await new Promise(r => server.listen(0, '127.0.0.1', r)); t.after(async () => { await new Promise(r => server.close(r)); await fs.rm(dir, { recursive: true }); }); return { filePath, baseURL: `http://127.0.0.1:${server.address().port}`, allowLoopback: true, apiKey: 'fixture-key' }; }
function reply(res, data, status = 200) { res.writeHead(status, { 'Content-Type': 'application/json' }); res.end(JSON.stringify(data)); }
test('OpenAI multipart sends key only in header and preserves timings', async t => { const opts = await fixture(t, (req, body, res) => { assert.equal(req.url, '/v1/audio/transcriptions'); assert.equal(req.headers.authorization, 'Bearer fixture-key'); assert.match(req.headers['content-type'], /^multipart\/form-data/); assert.match(body.toString(), /name="model"/); assert.doesNotMatch(body.toString(), /fixture-key/); reply(res, { text: 'Hello.', words: [{ word: 'Hello', start: 0.1, end: 0.5 }] }); }); const result = await transcribe({ ...opts, provider: 'openai' }); assert.equal(result.words[0].start, 0.1); });
test('Deepgram raw bytes, encoded parameters, speaker and utterance normalization', async t => { const opts = await fixture(t, (req, body, res) => { assert.equal(req.headers.authorization, 'Token fixture-key'); assert.equal(body.toString(), 'RIFFfixture'); assert.equal(new URL(req.url, 'http://localhost').searchParams.get('language'), 'en&evil=true'); reply(res, { metadata: { duration: 2 }, results: { channels: [{ alternatives: [{ transcript: 'Hello.', words: [{ punctuated_word: 'Hello.', start: 0, end: 1, speaker: 0 }] }] }], utterances: [{ transcript: 'Hello.', start: 0, end: 1, speaker: 0 }] } }); }); const result = await transcribe({ ...opts, provider: 'deepgram', language: 'en&evil=true', diarize: true }); assert.equal(result.words[0].speaker, '0'); assert.equal(result.segments.length, 1); });
test('AssemblyAI upload and polling normalize milliseconds', async t => { let count = 0; const opts = await fixture(t, (req, body, res) => { assert.equal(req.headers.authorization, 'fixture-key'); if (req.url === '/v2/upload') reply(res, { upload_url: 'https://cdn.assemblyai.com/audio.wav' }); else if (req.method === 'POST') { assert.equal(JSON.parse(body).audio_url, 'https://cdn.assemblyai.com/audio.wav'); reply(res, { id: 'abc', status: 'queued' }); } else if(req.method==='DELETE') reply(res,{}); else { count++; reply(res, { status: 'completed', text: 'Hello', words: [{ text: 'Hello', start: 500, end: 1000 }] }); } }); const result = await transcribe({ ...opts, provider: 'assemblyai', pollIntervalMs: 1 }); assert.equal(count, 1); assert.equal(result.words[0].start, 0.5); });
test('HTTP errors do not echo secrets or provider body', async t => { const opts = await fixture(t, (req, body, res) => reply(res, { error: 'fixture-key' }, 401)); await assert.rejects(transcribe({ ...opts, provider: 'groq' }), /^Error: Speech provider HTTP 401$/); });
test('cancel interrupts polling', async t => { const controller = new AbortController(); const opts = await fixture(t, (req, body, res) => req.url === '/v2/upload' ? reply(res, { upload_url: 'https://cdn.example/audio' }) : reply(res, { id: 'job', status: 'processing' })); await assert.rejects(transcribe({ ...opts, provider: 'assemblyai', signal: controller.signal, onProgress: () => controller.abort(new Error('fixture cancel')) }), /fixture cancel/); });
test('rejects endpoint credentials, remote HTTP, header injection and unknown formats', async t => { assert.throws(() => endpoint('http://example.com', '/', true)); assert.throws(() => endpoint('https://key@example.com', '/')); const opts = await fixture(t, (req, body, res) => reply(res, { text: 'never' })); await assert.rejects(transcribe({ ...opts, provider: 'openai', apiKey: 'a\r\nb' }), /Invalid API key/); await assert.rejects(transcribe({ ...opts, provider: 'sarvam' }), /verified duration/); await assert.rejects(transcribe({ ...opts, provider: 'openrouter' }), /Invalid model/); });
test('invalid timings are omitted and Gemini has no fabricated timestamps', () => { const result = normalize('gemini', { candidates: [{ content: { parts: [{ text: 'Hi' }] } }] }); assert.deepEqual(result.words, []); assert.deepEqual(normalize('openai', { text: 'Hi', words: [{ word: 'bad', start: -1, end: 3 }] }).words, []); });
for (const [provider, route, header, model, extra] of [
 ['groq','/openai/v1/audio/transcriptions','authorization','whisper-large-v3-turbo',{}],
 ['mistral','/v1/audio/transcriptions','authorization','voxtral-mini-latest',{}],
 ['elevenlabs','/v1/speech-to-text','xi-api-key','scribe_v2',{}],
 ['sarvam','/speech-to-text','api-subscription-key','saaras:v4',{duration:2}],
 ['xai','/v1/stt','authorization','grok-voice-transcribe-2.0',{}],
 ['cartesia','/stt','authorization','ink-whisper',{apiVersion:'2026-08-14'}],
 ['openrouter','/api/v1/audio/transcriptions','authorization','provider/model',{}],
]) test(`${provider} protocol uses declared fields and route`, async t => { const opts = await fixture(t,(req,body,res) => { assert.equal(req.url,route); assert.ok(req.headers[header]); const text=body.toString(); assert.match(text,new RegExp(model)); if(provider==='elevenlabs')assert.match(text,/name="model_id"/); if(provider==='cartesia')assert.equal(req.headers['cartesia-version'],'2026-08-14'); if(provider==='xai')assert.ok(text.indexOf('name="model"')<text.indexOf('name="file"')); reply(res,{text:'Hello',language:'en',duration:2}); }); assert.equal((await transcribe({...opts,provider,model,...extra})).text,'Hello'); });
test('Gemini inline audio protocol safely encodes model and media',async t=>{const opts=await fixture(t,(req,body,res)=>{assert.equal(req.url,'/v1beta/models/gemini-test:generateContent');assert.equal(req.headers['x-goog-api-key'],'fixture-key');const data=JSON.parse(body);assert.equal(Buffer.from(data.contents[0].parts[1].inlineData.data,'base64').toString(),'RIFFfixture');reply(res,{candidates:[{content:{parts:[{text:'Hello'}]}}]});});assert.equal((await transcribe({...opts,provider:'gemini',model:'gemini-test'})).text,'Hello');await assert.rejects(transcribe({...opts,provider:'gemini',model:'../bad'}),/Invalid Gemini model/);});
test('redirects never forward API credentials',async t=>{const opts=await fixture(t,(req,body,res)=>{res.writeHead(302,{location:'http://127.0.0.1:1/secret'});res.end();});await assert.rejects(transcribe({...opts,provider:'openai'}),/fetch failed/);});
test('nonempty and file limit checks occur before network',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'speech-limit-'));t.after(()=>fs.rm(dir,{recursive:true}));const filePath=path.join(dir,'large.wav');const handle=await fs.open(filePath,'w');await handle.truncate(25*1024**2+1);await handle.close();await assert.rejects(transcribe({provider:'openai',filePath,apiKey:'fixture'}),/at most/);await fs.writeFile(filePath,'');await assert.rejects(transcribe({provider:'openai',filePath,apiKey:'fixture'}),/nonempty/);});
test('Soniox asynchronous file, token milliseconds and own-resource cleanup',async t=>{const deleted=[];let polls=0;const opts=await fixture(t,(req,body,res)=>{assert.equal(req.headers.authorization,'Bearer fixture-key');if(req.method==='DELETE'){deleted.push(req.url);res.writeHead(204);res.end();}else if(req.url==='/v1/files'){assert.match(body.toString(),/name="file"/);reply(res,{id:'own-file'});}else if(req.method==='POST'){const payload=JSON.parse(body);assert.equal(payload.file_id,'own-file');assert.equal(payload.enable_speaker_diarization,true);reply(res,{id:'own-job',status:'queued'});}else if(req.url.endsWith('/transcript'))reply(res,{text:'Hello there.',tokens:[{text:'Hello',start_ms:100,end_ms:500,speaker:'1'},{text:' there.',start_ms:500,end_ms:900,speaker:'1'}]});else{polls++;reply(res,{status:'completed',audio_duration_ms:1000});}});const result=await transcribe({...opts,provider:'soniox',diarize:true,pollIntervalMs:1});assert.equal(polls,1);assert.equal(result.words[0].start,.1);assert.equal(result.duration,1);assert.deepEqual(deleted,['/v1/transcriptions/own-job','/v1/files/own-file']);assert.ok(result.cleanup.every(x=>x.deleted));});
test('Speechmatics config, polling and punctuation preserve readable transcript',async t=>{const opts=await fixture(t,(req,body,res)=>{if(req.method==='DELETE')reply(res,{});else if(req.method==='POST'){assert.equal(req.url,'/v2/jobs');assert.match(body.toString(),/name="data_file"/);assert.match(body.toString(),/"diarization":"speaker"/);reply(res,{id:'job1'});}else if(req.url.includes('/transcript')){assert.equal(req.url,'/v2/jobs/job1/transcript?format=json-v2');reply(res,{results:[{type:'word',start_time:0,end_time:.5,alternatives:[{content:'Hello',speaker:'S1'}]},{type:'punctuation',start_time:.5,end_time:.5,alternatives:[{content:','}]},{type:'word',start_time:.5,end_time:1,alternatives:[{content:'world',speaker:'S1'}]},{type:'punctuation',start_time:1,end_time:1,alternatives:[{content:'.'}]}]});}else reply(res,{job:{status:'done'}});});const result=await transcribe({...opts,provider:'speechmatics',language:'en',diarize:true});assert.equal(result.text,'Hello, world.');assert.equal(result.words.length,2);assert.equal(result.words[0].speaker,'S1');assert.equal(result.cleanup[0].deleted,true);});
test('cancel uses independent cleanup signal and reports refused Soniox deletion',async t=>{const controller=new AbortController();const deleted=[];let cleanup;const opts=await fixture(t,(req,body,res)=>{if(req.method==='DELETE'){deleted.push(req.url);reply(res,{error:'still processing'},409);}else if(req.url==='/v1/files')reply(res,{id:'f1'});else reply(res,{id:'j1',status:'processing'});});await assert.rejects(transcribe({...opts,provider:'soniox',signal:controller.signal,onProgress:()=>controller.abort(new Error('cancelled fixture')),onCleanup:r=>{cleanup=r;}}),/cancelled fixture/);assert.equal(deleted.length,2);assert.ok(cleanup.every(x=>x.deleted===false));});
test('malicious async job IDs cannot escape path or delete unrelated resources',async t=>{let deletes=0;const opts=await fixture(t,(req,body,res)=>{if(req.method==='DELETE'){deletes++;reply(res,{});}else reply(res,{id:'../unrelated',status:'completed'});});await assert.rejects(transcribe({...opts,provider:'speechmatics'}),/Invalid transcription job ID/);assert.equal(deletes,0);});
