'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');const {chat,buildRequest,normalize}=require('../src/main/cloud-ai');
const base={apiKey:'fixture-key',model:'fixture-model',messages:[{role:'system',content:'system instructions'},{role:'user',content:'hello'},{role:'assistant',content:'previous'},{role:'user',content:'now'}],images:[{mimeType:'image/png',data:Buffer.from('fixture-image').toString('base64')}]};
async function fixture(t,handler){const server=http.createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;handler(req,JSON.parse(body),res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return{...base,baseURL:`http://127.0.0.1:${server.address().port}`,allowLoopback:true};}
function reply(res,data,status=200){res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));}
for(const provider of ['openai','groq','deepseek','openrouter','cerebras','custom'])test(`${provider} compatible chat endpoint constructs declared roles and images`,async t=>{const opts=await fixture(t,(req,body,res)=>{assert.equal(req.url,'/chat/completions');assert.equal(req.headers.authorization,'Bearer fixture-key');assert.equal(body.messages[0].role,'system');assert.equal(body.stream,false);if(provider!=='deepseek')assert.match(body.messages[3].content[1].image_url.url,/^data:image\/png;base64,/);reply(res,{choices:[{message:{content:'answer'},finish_reason:'stop'}],usage:{total_tokens:2}});});assert.equal((await chat({...opts,provider,...(provider==='deepseek'?{images:[]}: {})})).text,'answer');});
test('native Anthropic keeps system outside messages and base64 image source',async t=>{const opts=await fixture(t,(req,body,res)=>{assert.equal(req.url,'/v1/messages');assert.equal(req.headers['x-api-key'],'fixture-key');assert.equal(req.headers['anthropic-version'],'2023-06-01');assert.equal(body.system,'system instructions');assert.ok(body.messages.every(m=>m.role!=='system'));assert.equal(body.messages[2].content[1].source.media_type,'image/png');reply(res,{content:[{type:'thinking',thinking:'hidden'},{type:'text',text:'answer'}],stop_reason:'end_turn'});});assert.equal((await chat({...opts,provider:'anthropic'})).text,'answer');});
test('Gemini native system, model role, inline images and thought exclusion',async t=>{const opts=await fixture(t,(req,body,res)=>{assert.equal(req.url,'/v1beta/models/fixture-model:generateContent');assert.equal(req.headers['x-goog-api-key'],'fixture-key');assert.equal(body.contents[1].role,'model');assert.equal(body.systemInstruction.parts[0].text,'system instructions');assert.equal(body.contents[2].parts[1].inlineData.mimeType,'image/png');reply(res,{candidates:[{content:{parts:[{thought:true,text:'hidden'},{text:'answer'}]},finishReason:'STOP'}]});});assert.equal((await chat({...opts,provider:'gemini'})).text,'answer');});
test('Azure deployment path and API-key auth',async t=>{const opts=await fixture(t,(req,body,res)=>{assert.equal(req.url,'/openai/deployments/my-deployment/chat/completions?api-version=2024-10-21');assert.equal(req.headers['api-key'],'fixture-key');assert.equal(body.model,undefined);reply(res,{choices:[{message:{content:'answer'}}]});});assert.equal((await chat({...opts,provider:'azure',deployment:'my-deployment',apiVersion:'2024-10-21'})).text,'answer');});
test('Bedrock native Converse bearer API key and image bytes',async t=>{const opts=await fixture(t,(req,body,res)=>{assert.equal(req.url,'/model/fixture-model/converse');assert.equal(req.headers.authorization,'Bearer fixture-key');assert.equal(body.system[0].text,'system instructions');assert.equal(body.messages[2].content[1].image.format,'png');reply(res,{output:{message:{content:[{text:'answer'}]}},stopReason:'end_turn'});});assert.equal((await chat({...opts,provider:'bedrock'})).text,'answer');});
test('path injection, unsupported provider, header injection, media and HTTPS validation',()=>{assert.throws(()=>buildRequest({...base,provider:'gemini',model:'../bad'}),/Invalid Gemini/);assert.throws(()=>buildRequest({...base,provider:'azure',baseURL:'https://trusted.example',apiVersion:'2024-10-21',deployment:'../other'}),/Invalid Azure/);assert.throws(()=>buildRequest({...base,provider:'openai',apiKey:'bad\r\nkey'}),/Invalid API/);assert.throws(()=>buildRequest({...base,provider:'deepseek'}),/does not support images/);assert.throws(()=>buildRequest({...base,provider:'openai',baseURL:'http://untrusted.example'}),/HTTPS/);assert.throws(()=>buildRequest({...base,provider:'claude-code'}),/Unsupported/);assert.throws(()=>buildRequest({...base,provider:'openai',images:[{mimeType:'image/png',data:'junk!'}]}),/Invalid/);});
test('HTTP failures redact provider response',async t=>{const opts=await fixture(t,(req,body,res)=>reply(res,{error:'fixture-key'},401));await assert.rejects(chat({...opts,provider:'openai'}),/^Error: AI provider HTTP 401$/);});
test('already aborted requests cancel without provider inference',async t=>{const opts=await fixture(t,()=>assert.fail('unexpected network'));const controller=new AbortController();controller.abort(new Error('fixture cancel'));await assert.rejects(chat({...opts,provider:'openai',signal:controller.signal}),/fixture cancel/);});
test('empty refusals are explicit errors and compatible base paths preserved',()=>{assert.throws(()=>normalize('gemini',{candidates:[]}),/no text/);assert.equal(buildRequest({...base,provider:'custom',baseURL:'https://trusted.example/custom/v1'}).url,'https://trusted.example/custom/v1/chat/completions');});
