'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),sharp=require('sharp');
const {performUtility}=require('../src/main/utilities');const {parseFileCommand}=require('../src/main/file-command');const ff=require('../src/main/ffmpeg').ffmpegExecutable();
let dir,codec;test.before(async()=>{dir=await fs.mkdtemp(path.join(os.tmpdir(),'scribble-format-'));codec=path.join(dir,'codec');if(process.platform==='darwin'){const r=cp.spawnSync('swiftc',['-O','-sdk','/Library/Developer/CommandLineTools/SDKs/MacOSX26.5.sdk','native/ImageCodec.swift','-o',codec],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);process.env.SCRIBBLE_IMAGE_CODEC=codec;}});test.after(async()=>{delete process.env.SCRIBBLE_IMAGE_CODEC;await fs.rm(dir,{recursive:true,force:true});});
function ffRun(args){const r=cp.spawnSync(ff,['-hide_banner','-nostdin',...args],{encoding:'utf8',timeout:30000});assert.equal(r.status,0,r.stderr);return r.stderr;}
test('documented image formats have concrete encodings, strict JFIF and preserve animated GIF',async()=>{const input=path.join(dir,'color.png');await sharp({create:{width:64,height:48,channels:3,background:'#4477bb'}}).png().toFile(input);for(const format of ['jpg','png','webp','avif','gif','tiff','jfif',...(process.platform==='darwin'?['heic','heif']:[])]){const output=path.join(dir,'out.'+format);const r=await performUtility({operation:'image-convert',files:[input],output});assert.equal(r.details.format,format);assert.equal(r.details.quality,80);let decode=output;if(['heic','heif'].includes(format)){decode=output+'.png';const n=cp.spawnSync(codec,[output,decode,'png','100'],{encoding:'utf8'});assert.equal(n.status,0,n.stderr);assert.equal((await fs.readFile(output)).subarray(8,12).toString(),'heic');const back=path.join(dir,'back-'+format+'.webp');await performUtility({operation:'image-convert',files:[output],output:back});assert.equal((await sharp(back).metadata()).width,64);const palette=await performUtility({operation:'image-palette',files:[output],output:output+'.palette.json'});assert.ok(palette.details.colors.length>0);}assert.equal((await sharp(decode).metadata()).width,64);await sharp(decode).raw().toBuffer();if(format==='jfif')assert.ok((await fs.readFile(output)).includes(Buffer.from('JFIF\0')));assert.ok(parseFileCommand('convert image from png to '+format));}
const animation=path.join(dir,'animated.gif');await sharp(Buffer.concat([Buffer.alloc(64*48*3,20),Buffer.alloc(64*48*3,220)]),{raw:{width:64,height:96,channels:3,pageHeight:48}}).gif({delay:[100,200]}).toFile(animation);const output=path.join(dir,'compressed.gif');await performUtility({operation:'image-compress',files:[animation],output});assert.equal((await sharp(output,{animated:true}).metadata()).pages,2);await assert.rejects(performUtility({operation:'image-compress',files:[input],output:path.join(dir,'wrong.webp')}),/preserves/);await assert.rejects(performUtility({operation:'image-convert',files:[input],output:input}),/replace/);await assert.rejects(performUtility({operation:'image-convert',files:[input],output:path.join(dir,'bad.xyz')}),/Unsupported/);
});
test('seven audio and video containers decode actual generated streams with xerror',async()=>{const audio=path.join(dir,'source.wav'),video=path.join(dir,'source.mp4');ffRun(['-y','-f','lavfi','-i','sine=frequency=440:sample_rate=48000:duration=2','-ac','2',audio]);ffRun(['-y','-f','lavfi','-i','testsrc2=size=64x48:rate=10:duration=2','-i',audio,'-c:v','libx264','-c:a','aac','-shortest',video]);for(const format of ['mp3','wav','aac','flac','ogg','m4a','wma','opus']){const output=path.join(dir,'tone.'+format);await performUtility({operation:'audio-convert',files:[audio],output});const decoded=path.join(dir,format+'.pcm');ffRun(['-xerror','-i',output,'-f','s16le','-ac','1','-ar','16000',decoded]);const pcm=await fs.readFile(decoded);assert.ok(pcm.length>50000);assert.ok(pcm.some(b=>b!==0));assert.ok(parseFileCommand('convert audio from wav to '+format));}for(const format of ['mp4','avi','mov','mkv','webm','flv','wmv']){const output=path.join(dir,'video.'+format);await performUtility({operation:'video-convert',files:[video],output});ffRun(['-xerror','-i',output,'-f','null','-']);assert.ok(parseFileCommand('convert video from mp4 to '+format));}await assert.rejects(performUtility({operation:'video-convert',files:[audio],output:path.join(dir,'audio-video.mp4')}),/matches no streams|does not contain|Stream map/);});
test('native codec refuses relative, malformed and occupied outputs without modifying files',{skip:process.platform!=='darwin'},async()=>{const input=path.join(dir,'native.png');await sharp({create:{width:16,height:16,channels:3,background:'red'}}).png().toFile(input);const occupied=path.join(dir,'occupied.png');await fs.writeFile(occupied,'preserve');for(const args of [[input,occupied,'png','80'],['relative.png',path.join(dir,'relative-out.png'),'png','80'],[input,path.join(dir,'badquality.png'),'png','NaN']]){const r=cp.spawnSync(codec,args,{encoding:'utf8'});assert.notEqual(r.status,0);}assert.equal(await fs.readFile(occupied,'utf8'),'preserve');const linked=path.join(dir,'dangling.png');await fs.symlink(path.join(dir,'absent.png'),linked);const r=cp.spawnSync(codec,[input,linked,'png','80'],{encoding:'utf8'});assert.notEqual(r.status,0);assert.ok((await fs.lstat(linked)).isSymbolicLink());});

test('PNG bytes renamed HEIC are refused for conversion and compression without publishing output',{skip:process.platform!=='darwin'},async()=>{const input=path.join(dir,'disguised.heic');await sharp({create:{width:16,height:16,channels:3,background:'blue'}}).png().toFile(input);for(const operation of ['image-convert','image-compress']){const output=path.join(dir,operation+'.heic');await assert.rejects(performUtility({operation,files:[input],output}),/genuine HEVC HEIC/);await assert.rejects(fs.stat(output),{code:'ENOENT'});}});
