'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{spawn,spawnSync}=require('node:child_process'),readline=require('node:readline');
const binary=path.resolve(__dirname,'../release/native/scribble-bridge');
const options={skip:process.platform!=='darwin'||!fs.existsSync(binary),timeout:10000};
test('compiled native status is noninteractive and reports idle system audio',options,()=>{const result=spawnSync(binary,['--status'],{encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);const value=JSON.parse(result.stdout);assert.equal(value.systemRecording,false);assert.equal(value.systemPaused,false);assert.equal(typeof value.accessibility,'boolean');assert.equal(typeof value.screenRecording,'boolean');});
test('system pause/resume reject missing capture, stop is idempotent, EOF exits',options,async t=>{const child=spawn(binary,['--no-event-tap'],{stdio:['pipe','pipe','pipe']}),lines=readline.createInterface({input:child.stdout}),pending=new Map();let count=0;t.after(()=>{lines.close();child.kill();});lines.on('line',line=>{const reply=JSON.parse(line),resolve=pending.get(reply.id);if(resolve){pending.delete(reply.id);resolve(reply);}});const send=command=>new Promise(resolve=>{const id=String(++count);pending.set(id,resolve);child.stdin.write(JSON.stringify({id,command})+'\n');});for(const command of ['recordSystemPause','recordSystemResume']){const reply=await send(command);assert.equal(reply.ok,false);assert.match(reply.error,/No system recording/);}assert.equal((await send('recordSystemStop')).ok,true);const idle=await send('status');assert.equal(idle.result.systemRecording,false);assert.equal(idle.result.systemPaused,false);const exited=new Promise(resolve=>child.once('exit',resolve));child.stdin.end();assert.equal(await exited,0);});

function helper(t){const child=spawn(binary,['--no-event-tap'],{stdio:['pipe','pipe','pipe']}),lines=readline.createInterface({input:child.stdout}),pending=new Map();let count=0;t.after(()=>{lines.close();child.kill();});lines.on('line',line=>{const reply=JSON.parse(line),resolve=pending.get(reply.id);if(resolve){pending.delete(reply.id);resolve(reply);}});return {child,send:(command,args={})=>new Promise(resolve=>{const id=String(++count);pending.set(id,resolve);child.stdin.write(JSON.stringify({...args,id,command})+'\n');})};}
test('editing dry runs map supported actions without posting desktop events',options,async t=>{const h=helper(t);for(const [action,key]of [['undo',6],['redo',6],['selectAll',0],['find',3]]){const reply=await h.send('edit',{action,dryRun:true});assert.equal(reply.ok,true);assert.equal(reply.result.dispatched,false);assert.equal(reply.result.verified,false);assert.equal(reply.result.keyCode,key);assert.equal(reply.result.requiresAccessibility,true);}const invalid=await h.send('edit',{action:'deleteEverything',dryRun:true});assert.equal(invalid.ok,false);assert.match(invalid.error,/Unsupported edit action/);});
test('editing rejects unavailable permission or changed target before any event is sent',options,async t=>{const h=helper(t);const reply=await h.send('edit',{action:'undo',expectedPid:-1});assert.equal(reply.ok,false);assert.match(reply.error,/Accessibility permission|active application changed|No frontmost application/);});
test('invalid or duplicate hotkey replacement preserves the current valid configuration',options,async t=>{const h=helper(t),bindings=[{keyCode:49,modifiers:['option'],mode:'dictation',toggle:false},{keyCode:49,modifiers:['option','shift'],mode:'dictation',toggle:true},{keyCode:-1,modifiers:['fn'],mode:'command',toggle:false}];const good=await h.send('setHotkeys',{hotkeys:bindings});assert.equal(good.ok,true);assert.equal(good.result.hotkeys,false);assert.equal(good.result.hotkeyBindings.length,3);assert.deepEqual(good.result.hotkeyBindings.map(x=>x.active),[false,false,false]);for(const bad of [[{keyCode:999,modifiers:['option'],mode:'dictation'}],[bindings[0],bindings[0]],[{keyCode:49,modifiers:['typo'],mode:'dictation'}]]){const reply=await h.send('setHotkeys',{hotkeys:bad});assert.equal(reply.ok,false);const state=await h.send('status');assert.deepEqual(state.result.hotkeyBindings,good.result.hotkeyBindings);}const cleared=await h.send('setHotkeys',{hotkeys:[]});assert.equal(cleared.ok,true);assert.equal(cleared.result.hotkeyBindings.length,0);});
test('rich/plain paste planning preserves format intent without clipboard or keyboard actions',options,async t=>{const h=helper(t);const rich=await h.send('paste',{text:'Hello world',html:'<p>Hello <strong>world</strong></p>',restoreClipboard:true,autoEnter:true,dryRun:true});assert.equal(rich.ok,true);assert.equal(rich.result.method,'clipboard-rich');assert.equal(rich.result.dispatched,false);assert.equal(rich.result.inserted,false);assert.equal(rich.result.verified,false);assert.deepEqual(rich.result.clipboardTypes,['public.utf8-plain-text','public.html']);assert.equal(rich.result.restoreClipboard,true);const plain=await h.send('paste',{text:'Plain text',html:'',dryRun:true});assert.equal(plain.result.method,'accessibility-or-clipboard-plain');assert.deepEqual(plain.result.clipboardTypes,['public.utf8-plain-text']);});
test('paste refuses unavailable permission or changed target without reporting insertion',options,async t=>{const h=helper(t);const reply=await h.send('paste',{text:'Never inserted',html:'<b>Never inserted</b>',expectedPid:-1});assert.equal(reply.ok,true);assert.equal(reply.result.inserted,false);assert.equal(reply.result.dispatched,false);assert.equal(reply.result.method,'none');assert.match(reply.result.reason,/Accessibility permission|active application changed/);});
test('clipboard restoration preserves multiple items, HTML and binary types without overwriting new copies',options,()=>{const result=spawnSync(binary,['--clipboard-self-test'],{encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);assert.deepEqual(JSON.parse(result.stdout),{ok:true,privatePasteboard:true});});
test('expansion templates substitute selection/date/clipboard while escaping dynamic rich values',options,()=>{const result=spawnSync(binary,['--template-self-test'],{encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);const value=JSON.parse(result.stdout);assert.equal(value.plain,'October 7, 2026 9:30 AM Selected <words> Selected <words> <b>Clipboard & text</b>');assert.equal(value.html,'<strong>&lt;b&gt;Clipboard &amp; text&lt;/b&gt;</strong><p>Selected &lt;words&gt;</p>');assert.equal(value.literal,'{date}');});
test('frontmost context reports bounded URL evidence or an explicit unavailable source',options,async t=>{const h=helper(t),reply=await h.send('frontmost');assert.equal(reply.ok,true);assert.equal(typeof reply.result.name,'string');assert.equal(typeof reply.result.bundleId,'string');assert.equal(typeof reply.result.pid,'number');assert.equal(typeof reply.result.urlAvailable,'boolean');assert.equal(typeof reply.result.urlSource,'string');if(reply.result.urlAvailable){const url=new URL(reply.result.url);assert.ok(['http:','https:'].includes(url.protocol));assert.equal(url.search,'');assert.equal(url.hash,'');assert.equal(url.username,'');}else assert.equal(reply.result.url,'');});
test('frontmost URL normalization removes tokens and refuses credentials or non-web documents',options,()=>{const result=spawnSync(binary,['--context-url-self-test'],{encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);assert.deepEqual(JSON.parse(result.stdout),{clean:'https://example.com/work',credentialed:true,nonWeb:true});});
test('hotkey tone metadata accompanies start/stop without generating desktop events',options,()=>{const result=spawnSync(binary,['--hotkey-tone-self-test'],{encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);const events=result.stdout.trim().split('\n').map(x=>JSON.parse(x));assert.deepEqual(events.map(x=>x.phase),['start','stop']);for(const event of events){assert.equal(event.event,'hotkey');assert.equal(event.mode,'dictation');assert.equal(event.toneId,'tone-fixture');}});
test('auxiliary mouse bindings validate sentinels atomically and status reports their input kind',options,async t=>{const h=helper(t);const reply=await h.send('setHotkeys',{hotkeys:[{keyCode:130,modifiers:[],mode:'dictation',toggle:false},{keyCode:159,modifiers:['shift'],mode:'command',toggle:true}]});assert.equal(reply.ok,true);assert.deepEqual(reply.result.hotkeyBindings.map(x=>({keyCode:x.keyCode,inputKind:x.inputKind,active:x.active,toggle:x.toggle})),[{keyCode:130,inputKind:'mouse',active:false,toggle:false},{keyCode:159,inputKind:'mouse',active:false,toggle:true}]);assert.equal(typeof reply.result.hotkeys,'boolean');for(const keyCode of [128,129,160,-2,130.5,true,"130"]){const rejected=await h.send('setHotkeys',{hotkeys:[{keyCode,modifiers:[],mode:'dictation'}]});assert.equal(rejected.ok,false);const status=await h.send('status');assert.deepEqual(status.result.hotkeyBindings.map(x=>x.keyCode),[130,159]);}});
test('synthetic auxiliary events handle hold, modifier release, toggle, repeats and preserve primary/unbound buttons',options,()=>{const result=spawnSync(binary,['--mouse-hotkey-self-test'],{encoding:'utf8',timeout:5000});assert.equal(result.status,0,result.stderr);const lines=result.stdout.trim().split('\n').map(JSON.parse);const summary=lines.pop();assert.deepEqual(summary,{selfTest:'mouse-hotkeys',holdConsumed:true,repeatConsumed:true,modifierReleasePassed:true,releasedHold:true,toggleConsumed:true,toggleInactive:true,unboundPassed:true,primaryPassed:true,highestConsumed:true,consumedCount:0});assert.deepEqual(lines.map(x=>[x.mode,x.phase]),[['dictation','start'],['dictation','stop'],['command','start'],['command','stop'],['meeting','start'],['meeting','stop']]);});
