'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {JSDOM}=require('jsdom');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(t){const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../src/renderer/overlay.html'),'utf8'),{runScripts:'outside-only',url:'http://localhost/'});t.after(()=>dom.window.close());const w=dom.window,calls=[];let listener,unsubscribed=false,now=1000;w.Date.now=()=>now;w.scribble={on(fn){listener=fn;return()=>{unsubscribed=true;};},async request(action,args){calls.push({action,args});if(action==='state')return{settings:{indicatorStyle:'pill',indicatorPosition:'bottom',idleIndicator:false},tones:[]};return true;}};w.eval(fs.readFileSync(path.join(__dirname,'../src/shared/i18n.js'),'utf8'));w.eval(fs.readFileSync(path.join(__dirname,'../src/renderer/overlay.js'),'utf8'));await wait(5);return{w,calls,emit:(event,data)=>listener({event,data}),advance:ms=>now+=ms,unsubscribed:()=>unsubscribed,$:id=>w.document.getElementById(id)};}
test('overlay only displays actual recording-level samples and zeros missing telemetry',async t=>{const h=await fixture(t);h.emit('recording-state',{state:'recording',text:'Listening',style:'pill'});assert.equal(h.$('meter').getAttribute('aria-valuenow'),'0');h.emit('recording-level',{level:.25});assert.equal(h.$('meter').getAttribute('aria-valuenow'),'25');assert.equal(h.$('meter').children[3].style.height,'9px');h.advance(600);await wait(130);assert.equal(h.$('meter').getAttribute('aria-valuenow'),'0');assert.equal(h.$('meter').children[3].style.height,'3px');});
test('meter rejects malformed/out-of-range telemetry and suppresses paused or muted audio',async t=>{const h=await fixture(t);h.emit('recording-state',{state:'recording'});h.emit('audio-level',{rms:2,peak:1});assert.equal(h.$('meter').getAttribute('aria-valuenow'),'100');assert.equal(h.$('meter').classList.contains('clipped'),true);h.emit('audio-level',{rms:Infinity});assert.equal(h.$('meter').getAttribute('aria-valuenow'),'0');h.emit('audio-level',{rms:.8,muted:true});assert.equal(h.$('meter').getAttribute('aria-valuenow'),'0');assert.equal(h.$('meter').getAttribute('aria-valuetext'),'Muted');h.emit('recording-state',{state:'paused'});h.emit('recording-level',{level:.8});assert.equal(h.$('meter').getAttribute('aria-valuenow'),'0');});
test('pill, notch, hidden and opt-in idle visibility follow configuration',async t=>{const h=await fixture(t);assert.equal(h.$('indicator').hidden,true);h.emit('overlay-config',{idleIndicator:true,style:'notch'});assert.equal(h.$('indicator').hidden,false);assert.equal(h.$('indicator').dataset.style,'notch');h.emit('recording-state',{state:'recording',style:'hidden'});assert.equal(h.$('indicator').hidden,true);h.emit('recording-state',{state:'recording',style:'pill',position:'hidden'});assert.equal(h.$('indicator').hidden,true);h.emit('recording-state',{state:'processing',position:'bottom'});assert.equal(h.$('indicator').hidden,false);assert.equal(h.$('stop').hidden,true);assert.equal(h.$('cancel').hidden,false);});
test('idle and active controls dispatch existing main actions with correct recording mode',async t=>{const h=await fixture(t);h.emit('overlay-config',{idleIndicator:true});h.$('start').click();h.$('open').click();await wait(5);assert.equal(h.calls.find(x=>x.action==='start-recording').args.mode,'dictation');assert.ok(h.calls.find(x=>x.action==='show'));h.emit('recording-state',{state:'recording'});h.$('stop').click();h.$('cancel').click();await wait(5);assert.ok(h.calls.find(x=>x.action==='stop-recording'));assert.ok(h.calls.find(x=>x.action==='cancel-recording'));});
test('tone picker requires a genuine advertised action and handles names as text',async t=>{const h=await fixture(t);const tones=[{id:'t1',name:'<img src=x onerror=alert(1)>'},{id:'t2',name:'Concise'}];h.emit('recording-state',{state:'idle',tones,selectedTone:'t1',idleIndicator:true});assert.equal(h.$('tone').hidden,true);h.emit('overlay-config',{canSelectTone:true});assert.equal(h.$('tone').hidden,false);assert.equal(h.$('tone').textContent,'<img src=x onerror=alert(1)> ▾');assert.equal(h.$('tone').querySelector('img'),null);h.$('tone').click();await wait(5);assert.ok(h.calls.find(x=>x.action==='show-tone-menu'));assert.equal(h.calls.filter(x=>x.action==='select-tone').length,0);h.emit('recording-state',{state:'recording'});assert.equal(h.$('tone').hidden,true);});
test('overlay releases subscription and telemetry timer on page exit',async t=>{const h=await fixture(t);h.w.dispatchEvent(new h.w.Event('pagehide'));assert.equal(h.unsubscribed(),true);});

test('overlay language switch updates active status and accessible controls without resetting recording', async t => {
  const h=await fixture(t);
  h.emit('recording-state',{state:'recording',text:'Listening…',locale:'en'});
  h.emit('state',{settings:{locale:'ja',indicatorStyle:'pill',indicatorPosition:'bottom'},tones:[]});
  assert.equal(h.w.document.documentElement.lang,'ja');
  assert.equal(h.$('indicator').dataset.state,'recording');
  assert.equal(h.$('stop').hidden,false);
  assert.equal(h.$('text').textContent,h.w.ScribbleI18n.t('ja','overlay.listening'));
  assert.equal(h.$('stop').getAttribute('aria-label'),h.w.ScribbleI18n.t('ja','overlay.stopRecording'));
  h.emit('recording-state',{state:'error',text:'External provider: example detail'});
  assert.equal(h.$('text').textContent,'External provider: example detail');
});
