'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),sharp=require('sharp');const {paletteFromImages,LIMITS}=require('../src/main/screen-palette');
async function image(width,height,background,format='png'){const data=await sharp({create:{width,height,channels:4,background}}).toFormat(format).toBuffer();return {mimeType:'image/'+(format==='jpeg'?'jpeg':format),data:data.toString('base64'),width,height};}
test('combined generated frames preserve coherent sample weighting and return only color metadata',async()=>{const red=await image(128,64,'#ff0000'),blue=await image(64,64,'#0000ff');const result=await paletteFromImages([red,blue]);assert.equal(result.sourceCount,2);assert.equal(result.sampledPixels,12288);assert.deepEqual(result.colors.map(x=>x.hex),['#ff0000','#0000ff']);assert.deepEqual(result.colors.map(x=>x.count),[8192,4096]);assert.equal(result.colors[0].proportion,2/3);assert.equal(result.colors[1].proportion,1/3);assert.match(result.method,/sampled pixel count/);const text=JSON.stringify(result);assert.ok(!text.includes(red.data));assert.ok(!text.includes('mimeType'));assert.ok(!text.includes('pixels":['));});
test('transparent pixels are ignored and all-transparent images refuse an invented palette',async()=>{const transparent=await image(16,16,'#00000000'),green=await image(16,16,'#00ff00');const result=await paletteFromImages([transparent,green],{colors:1});assert.equal(result.sampledPixels,256);assert.equal(result.sources[0].visibleSampledPixels,0);assert.deepEqual(result.colors,[{hex:'#00ff00',rgb:[0,255,0],proportion:1,count:256}]);await assert.rejects(paletteFromImages([transparent]),/no visible/);});
test('bounded resize and genuine JPEG PNG WebP decoding',async()=>{for(const format of ['jpeg','png','webp']){const input=await image(1536,768,'#ff6600',format);const result=await paletteFromImages([input]);assert.equal(result.sources[0].sampleWidth,128);assert.equal(result.sources[0].sampleHeight,64);assert.equal(result.sampledPixels,8192);assert.ok(result.colors[0].rgb[0]>240);}});
test('invalid inputs, noncanonical base64, MIME mismatches, dimensions and resource limits refuse',async()=>{const valid=await image(16,16,'red');for(const images of [[],Array(6).fill(valid),[{...valid,mimeType:'image/gif'}],[{...valid,data:'notbase64'}],[{...valid,data:valid.data+'\n'}],[{...valid,mimeType:'image/jpeg'}],[{...valid,width:15}],[{...valid,data:Buffer.alloc(LIMITS.bytes+1).toString('base64')}],[{...valid,data:Buffer.from('notanimage').toString('base64')}]] )await assert.rejects(paletteFromImages(images));for(const colors of [0,17,1.5,NaN,'6'])await assert.rejects(paletteFromImages([valid],{colors}));const oversized=await image(1537,1,'red');await assert.rejects(paletteFromImages([oversized]),/dimensions/);});
test('five sources accepted and requested color cap is bounded',async()=>{const input=await image(16,16,'red');const result=await paletteFromImages(Array(5).fill(input),{colors:16});assert.equal(result.sourceCount,5);assert.equal(result.sampledPixels,1280);assert.equal(result.colors.length,1);});

test('animated image refuses instead of silently reducing a screen frame to one page',async()=>{const data=await sharp(Buffer.concat([Buffer.alloc(16*16*3,20),Buffer.alloc(16*16*3,200)]),{raw:{width:16,height:32,channels:3,pageHeight:16}}).webp({delay:[100,100]}).toBuffer();await assert.rejects(paletteFromImages([{mimeType:'image/webp',data:data.toString('base64')}]),/one frame/);});
