'use strict';
const { endpoint } = require('./cloud-speech');
const PROVIDERS = Object.freeze({ openai: 'https://api.openai.com/v1', groq: 'https://api.groq.com/openai/v1', deepseek: 'https://api.deepseek.com', openrouter: 'https://openrouter.ai/api/v1', cerebras: 'https://api.cerebras.ai/v1', anthropic: 'https://api.anthropic.com', gemini: 'https://generativelanguage.googleapis.com', azure: null, bedrock: null, custom: null });
function value(x,name,required=true) { if(x==null&&!required)return undefined; if(typeof x!=='string'||!x.trim()||/[\r\n\0]/.test(x)||x.length>4096)throw new Error(`Invalid ${name}`);return x; }
function image(x) { if(!x||!['image/png','image/jpeg','image/webp','image/gif'].includes(x.mimeType)||typeof x.data!=='string'||!x.data.length||!/^[A-Za-z0-9+/]*={0,2}$/.test(x.data)||x.data.length%4!==0||Buffer.from(x.data,'base64').length>4*1024**2)throw new Error('Invalid or oversized image');return {mimeType:x.mimeType,data:x.data}; }
function buildRequest(options) {
 const provider=options.provider;if(!Object.hasOwn(PROVIDERS,provider))throw new Error('Unsupported text AI provider');
 const model=value(options.model,'model'),key=value(options.apiKey,'API key');
 const history=options.messages||[{role:'user',content:options.prompt}];if(!Array.isArray(history)||!history.length||history.length>100)throw new Error('Invalid messages');
 const messages=history.map(m=>{if(!['user','assistant','system'].includes(m.role)||typeof m.content!=='string'||m.content.length>500000)throw new Error('Invalid message');return {role:m.role,content:m.content};});
 if(options.system){if(typeof options.system!=='string')throw new Error('Invalid system prompt');messages.unshift({role:'system',content:options.system});}
 const images=(options.images||[]).map(image);if(images.length>5)throw new Error('Too many images');
 if(images.length&&provider==='deepseek')throw new Error('DeepSeek text adapter does not support images');
 const maxTokens=options.maxTokens??2048;if(!Number.isInteger(maxTokens)||maxTokens<1||maxTokens>32768)throw new Error('Invalid maxTokens');
 const temperature=options.temperature;if(temperature!=null&&(!Number.isFinite(temperature)||temperature<0||temperature>2))throw new Error('Invalid temperature');
 const base=options.baseURL||PROVIDERS[provider];if(!base)throw new Error('Provider endpoint required');endpoint(base,'/',options.allowLoopback===true);
 const system=messages.filter(m=>m.role==='system').map(m=>m.content).join('\n\n');const turns=messages.filter(m=>m.role!=='system');if(!turns.length)throw new Error('User conversation required');
 const lastUser=turns.findLastIndex(m=>m.role==='user');if(images.length&&lastUser<0)throw new Error('Images require a user message');
 let route,body,headers={'Content-Type':'application/json'};
 if(provider==='anthropic') {route='/v1/messages';headers['x-api-key']=key;headers['anthropic-version']='2023-06-01';body={model,max_tokens:maxTokens,...(system?{system}:{}),messages:turns.map((m,i)=>({role:m.role,content:[{type:'text',text:m.content},...(i===lastUser?images.map(x=>({type:'image',source:{type:'base64',media_type:x.mimeType,data:x.data}})):[])]}))};}
 else if(provider==='gemini') {if(!/^[A-Za-z0-9._-]+$/.test(model))throw new Error('Invalid Gemini model');route=`/v1beta/models/${model}:generateContent`;headers['x-goog-api-key']=key;body={...(system?{systemInstruction:{parts:[{text:system}]}}:{}),contents:turns.map((m,i)=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content},...(i===lastUser?images.map(x=>({inlineData:x})):[])]})),generationConfig:{maxOutputTokens:maxTokens}};if(temperature!=null)body.generationConfig.temperature=temperature;}
 else if(provider==='bedrock') {if(!/^[A-Za-z0-9._:-]+$/.test(model))throw new Error('Invalid Bedrock model');route=`/model/${encodeURIComponent(model)}/converse`;headers.Authorization=`Bearer ${key}`;body={...(system?{system:[{text:system}]}:{}),messages:turns.map((m,i)=>({role:m.role,content:[{text:m.content},...(i===lastUser?images.map(x=>({image:{format:x.mimeType.slice(6),source:{bytes:x.data}}})):[])]})),inferenceConfig:{maxTokens,...(temperature!=null?{temperature}:{})}};}
 else {const nativeMessages=messages.map(m=>({...m}));if(images.length){const idx=nativeMessages.findLastIndex(m=>m.role==='user');nativeMessages[idx].content=[{type:'text',text:nativeMessages[idx].content},...images.map(x=>({type:'image_url',image_url:{url:`data:${x.mimeType};base64,${x.data}`}}))];}body={model,messages:nativeMessages,stream:false,...(['openai','azure','cerebras'].includes(provider)?{max_completion_tokens:maxTokens}:{max_tokens:maxTokens}),...(temperature!=null?{temperature}:{})};
 if(provider==='azure'){const deployment=value(options.deployment||model,'deployment');if(!/^[A-Za-z0-9._-]+$/.test(deployment))throw new Error('Invalid Azure deployment');const version=value(options.apiVersion,'Azure API version');if(!/^\d{4}-\d{2}-\d{2}(-preview)?$/.test(version))throw new Error('Invalid Azure API version');route=`/openai/deployments/${deployment}/chat/completions?api-version=${version}`;headers['api-key']=key;delete body.model;}else{route=`${new URL(base).pathname.replace(/\/$/,'')}/chat/completions`;headers.Authorization=`Bearer ${key}`;}}
 const serialized=JSON.stringify(body);if(Buffer.byteLength(serialized)>24*1024**2)throw new Error('AI request exceeds limit');return {url:endpoint(base,route,options.allowLoopback===true),headers,body:serialized,provider};
}
function normalize(provider,data){let text,finishReason;if(provider==='anthropic'){text=(data.content||[]).filter(p=>p.type==='text').map(p=>p.text).join('');finishReason=data.stop_reason;}else if(provider==='gemini'){text=(data.candidates?.[0]?.content?.parts||[]).filter(p=>!p.thought).map(p=>p.text||'').join('');finishReason=data.candidates?.[0]?.finishReason;}else if(provider==='bedrock'){text=(data.output?.message?.content||[]).map(p=>p.text||'').join('');finishReason=data.stopReason;}else{text=data.choices?.[0]?.message?.content;finishReason=data.choices?.[0]?.finish_reason;}if(typeof text!=='string'||!text.trim())throw new Error('AI provider returned no text');return {text,finishReason:finishReason||null,usage:data.usage||data.usageMetadata||null,provider};}
async function chat(options){const request=buildRequest(options);const controller=new AbortController();const abort=()=>controller.abort(options.signal?.reason);options.signal?.addEventListener('abort',abort,{once:true});if(options.signal?.aborted)abort();const timer=setTimeout(()=>controller.abort(new Error('AI request timed out')),Math.min(Math.max(options.timeoutMs||120000,1),900000));try{const response=await fetch(request.url,{method:'POST',headers:request.headers,body:request.body,signal:controller.signal,redirect:'error'});let size=0;const chunks=[];for await(const chunk of response.body||[]){size+=chunk.length;if(size>8*1024**2){controller.abort();throw new Error('AI response exceeds limit');}chunks.push(chunk);}if(!response.ok)throw new Error(`AI provider HTTP ${response.status}`);let data;try{data=JSON.parse(Buffer.concat(chunks).toString());}catch{throw new Error('AI provider returned invalid JSON');}return normalize(request.provider,data);}finally{clearTimeout(timer);options.signal?.removeEventListener('abort',abort);}}
module.exports={PROVIDERS,buildRequest,normalize,chat};
