'use strict';
const {app,BrowserWindow,ipcMain,dialog,Tray,Menu,nativeImage,Notification,shell,clipboard,safeStorage,protocol,net,desktopCapturer,systemPreferences}=require('electron');
const fs=require('node:fs'),fsp=fs.promises,path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),http=require('node:http'),{spawn}=require('node:child_process');
const {Store}=require('./store'),{SpeechEngine}=require('./speech'),{NativeBridge}=require('./native'),domain=require('./domain'),ai=require('./ai');
protocol.registerSchemesAsPrivileged([{scheme:'scribble-audio',privileges:{standard:true,secure:true,supportFetchAPI:true,stream:true}}]);
app.setName('Scribble');
const lock=app.requestSingleInstanceLock();if(!lock){app.quit();process.exit(0);}
let window,overlay,tray,store,speech,native,dataDir,server,recordTarget=null,activeMode='dictation',systemRecording=null,quitting=false;const timers=new Map(),allowedFiles=new Set();
function emit(event,data){for(const w of [window,overlay])if(w&&!w.isDestroyed())w.webContents.send('scribble:event',{event,data});}
function notify(title,body){if(Notification.isSupported())new Notification({title,body}).show();emit('notice',{title,body});}
function show(){if(!window||window.isDestroyed())createWindow();window.show();window.focus();}
function snapshot(){return{...store.data,models:speech.listModels(),speechStatus:speech.status(),nativeAvailable:native.available,stats:domain.computeStats(store.data.history),version:app.getVersion(),dataDir,platform:process.platform};}
function createWindow(){window=new BrowserWindow({width:1240,height:850,minWidth:940,minHeight:660,title:'Scribble',backgroundColor:'#f8f9fc',titleBarStyle:'hiddenInset',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});window.loadFile(path.join(__dirname,'../renderer/index.html'));window.on('close',e=>{if(!quitting){e.preventDefault();window.hide();}});window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.webContents.on('did-finish-load',()=>emit('state',snapshot()));}
function createOverlay(){overlay=new BrowserWindow({width:360,height:90,show:false,frame:false,transparent:true,resizable:false,alwaysOnTop:true,skipTaskbar:true,focusable:false,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});overlay.setVisibleOnAllWorkspaces(true,{visibleOnFullScreen:true});overlay.loadFile(path.join(__dirname,'../renderer/overlay.html'));}
function indicator(state,text){if(!overlay||overlay.isDestroyed())return;if(store.data.settings.indicatorPosition==='hidden'){overlay.hide();return;}const {screen}=require('electron');const display=screen.getDisplayNearestPoint(screen.getCursorScreenPoint()).workArea;overlay.setPosition(Math.round(display.x+(display.width-360)/2),store.data.settings.indicatorPosition==='top'?display.y+15:display.y+display.height-110);if(state==='idle'&&!store.data.settings.idleIndicator)overlay.hide();else overlay.showInactive();emit('recording-state',{state,text,mode:activeMode});}
function apiKey(){const file=path.join(dataDir,'provider.key');if(!fs.existsSync(file))return'';if(!safeStorage.isEncryptionAvailable())throw Error('Secure key storage is unavailable');return safeStorage.decryptString(fs.readFileSync(file));}
function updateNative(){if(!native.available)return;native.request('setHotkeys',{hotkeys:store.data.settings.hotkeys}).catch(e=>emit('native-error',e.message));native.request('setExpansions',{expansions:store.data.settings.expansionsEnabled?store.data.expansions.filter(x=>x.enabled!==false).map(x=>({trigger:x.trigger,replacement:x.replacement.replace(/\{\{DATE\}\}/g,'{date}').replace(/\{\{TIME\}\}/g,'{time}').replace(/\{\{CLIPBOARD\}\}/g,'{clipboard}')})):[]}).catch(()=>{});native.request('clipboardMonitoring',{enabled:store.data.settings.clipboardHistory}).catch(()=>{});}
async function beginRecording(mode='dictation'){if(recordTarget||speech.status().busy){emit('notice',{title:'Scribble is busy',body:'Finish the current recording or transcription first.'});return;}recordTarget={starting:true};const front=await native.request('frontmost').catch(()=>({}));if(store.data.settings.suppressedApps.includes(front.bundleId)){recordTarget=null;return;}recordTarget=front;activeMode=mode;emit('recording-control',{action:'start',mode});indicator('starting','Starting microphone…');}
async function openUrl(url){const parsed=new URL(url);if(!['http:','https:','mailto:'].includes(parsed.protocol))throw Error('Only web and email links are supported');if(store.data.settings.preferredBrowser==='Google Chrome'&&process.platform==='darwin'&&parsed.protocol!=='mailto:'){await new Promise((resolve,reject)=>{const p=spawn('/usr/bin/open',['-a','Google Chrome',url]);p.on('error',reject);p.on('exit',c=>c?reject(Error('Chrome could not open the link')):resolve());});}else await shell.openExternal(url);}
async function pasteText(text){if(!text)return;if(native.available)return native.request('paste',{text,restoreClipboard:store.data.settings.restoreClipboard,autoEnter:store.data.settings.autoEnter});clipboard.writeText(text);return{inserted:false};}
function applyTone(settings,front){const tone=store.data.tones.find(t=>t.apps?.some(v=>v===front?.bundleId||v===front?.name));return tone?{...settings,modelId:tone.modelId||settings.modelId,aiInstructions:tone.instructions||settings.aiInstructions,aiEnhance:tone.enhance??settings.aiEnhance}:settings;}
async function enhance(text,settings){return ai.chat(settings,[{role:'system',content:settings.aiInstructions},{role:'user',content:text}],apiKey());}
async function runShortcut(text){const match=domain.matchShortcut(text,store.data.shortcuts);if(!match)return null;const shortcut=match.shortcut||match;let query=match.query??match.text??text.slice(shortcut.trigger.length).trim();const target=shortcut.target||shortcut.url;if(target==='navigate'){let url=query.replace(/\s+/g,'').replace(/ dot /gi,'.');if(!url)throw Error('Say a website after “navigate to”');if(!/^https?:/i.test(url))url='https://'+url;await openUrl(url);}else if(target==='folder'){const dirs={downloads:'Downloads',desktop:'Desktop',documents:'Documents',pictures:'Pictures',music:'Music',movies:'Movies',home:''};const folder=dirs[query.toLowerCase()];if(folder===undefined)return null;await shell.openPath(path.join(os.homedir(),folder));}else if(shortcut.type==='app'){await new Promise((resolve,reject)=>{const p=spawn('/usr/bin/open',['-a',target]);p.on('error',reject);p.on('exit',c=>c?reject(Error('Application could not be opened')):resolve());});}else if(shortcut.type==='folder'){await shell.openPath(target);}else await openUrl(target.replace(/\{\{text\}\}/g,encodeURIComponent(query)));return{action:shortcut.name||shortcut.trigger,query};}
async function runCommand(text,context=''){const timer=text.match(/(?:set |start )?(?:a )?timer (?:for )?(\d+)\s*(seconds?|minutes?|hours?)/i);if(timer){const seconds=Number(timer[1])*(timer[2].startsWith('hour')?3600:timer[2].startsWith('minute')?60:1);if(seconds<1||seconds>86400)throw Error('Timer must be between 1 second and 24 hours');const id=crypto.randomUUID(),endsAt=Date.now()+seconds*1000;const entry={id,title:`${timer[1]} ${timer[2]} timer`,endsAt};store.data.timers.push(entry);store.save();timers.set(id,setTimeout(()=>{store.data.timers=store.data.timers.filter(t=>t.id!==id);store.save();notify('Timer finished',entry.title);emit('state',snapshot());},seconds*1000));return{kind:'timer',text:`Timer set for ${timer[1]} ${timer[2]}.`};}const routed=await runShortcut(text);if(routed)return{kind:'shortcut',text:`Opened ${routed.action}.`};const target=context||await native.request('selection').then(x=>x.text).catch(()=>'' )||clipboard.readText();let result;
if(/^(uppercase|upper case|make (?:it )?uppercase)$/i.test(text.trim()))result=target.toLocaleUpperCase();else if(/^(lowercase|lower case|make (?:it )?lowercase)$/i.test(text.trim()))result=target.toLocaleLowerCase();else if(/^copy (?:selection|selected text)$/i.test(text)){clipboard.writeText(target);return{kind:'clipboard',text:'Copied selection.'};}else{const memory=store.data.settings.memoryEnabled?store.data.memory.filter(m=>m.enabled!==false).map(m=>`${m.name}: ${m.content}`).join('\n').slice(0,40000):'';result=await ai.chat(store.data.settings,[{role:'system',content:'You are Scribble, a precise writing assistant. Follow the user command using the provided text. Return only the requested final text. Never invent successful system actions. Reference material:\n'+memory},{role:'user',content:`Command: ${text}\n\nText:\n${target}`}],apiKey());}return{kind:'text',text:result,original:target};}
async function processFile(file,{kind='file',title,template,personalNotes='',flags=[],front=recordTarget}={}){const settings=applyTone(store.data.settings,front);indicator('processing','Transcribing locally…');const result=await speech.transcribe(file,{modelId:settings.modelId,language:settings.language,translate:settings.translate,prompt:store.data.dictionary.map(x=>x.word).join(', ')});let text=domain.normalizeTranscript(result.text,{dictionary:store.data.dictionary,threads:store.data.threads,removeFillers:settings.removeFillers,punctuation:settings.punctuation});const entry={...result,text,original:result.text,kind,title:title||path.basename(file),audioPath:settings.saveAudio?file:null,modelId:settings.modelId};if(kind==='command'){const command=await runCommand(text);entry.text=command.text;entry.command=text;entry.commandResult=command;emit('command-result',command);}else if(kind==='dictation'||kind==='shortcut'){const shortcut=await runShortcut(text);if(shortcut){entry.kind='shortcut';entry.action=shortcut.action;}else{if(settings.aiEnhance){try{entry.text=await enhance(text,settings);}catch(e){entry.warning='AI cleanup failed: '+e.message;}}if(settings.autoPaste)await pasteText(entry.text);}}
if(kind==='note'){let summary;try{summary=await ai.chat(settings,[{role:'system',content:`Summarize this ${template||'meeting'} in ${settings.summaryLanguage}. Return Markdown with overview, decisions, and action items. Preserve names, dates, owners and uncertainty. Do not invent events.`},{role:'user',content:text}],apiKey());}catch(e){summary=ai.extractiveSummary(text,template||'Meeting');entry.warning=e.message;}const note=store.upsert('notes',{title:title||'Untitled meeting',transcript:text,summary,segments:result.segments,audioPath:entry.audioPath,template:template||'Meeting',duration:result.duration,personalNotes,flags});entry.noteId=note.id;emit('navigate',{page:'notes',id:note.id});}
let saved=entry;if(settings.saveHistory||kind==='file'||kind==='note')saved=store.addHistory(entry);if(!settings.saveAudio&&file.startsWith(path.join(dataDir,'recordings')))await fsp.rm(file,{force:true});notify(kind==='note'?'Your notes are ready':'Transcription ready',entry.text.slice(0,120)||'No speech detected');emit('state',snapshot());indicator('idle','');return saved;}
const actions={
 'state':()=>snapshot(),
 'preferences':async patch=>{store.updateSettings(patch);if('launchAtLogin'in patch)app.setLoginItemSettings({openAtLogin:patch.launchAtLogin});if('hideDock'in patch&&app.dock)patch.hideDock?app.dock.hide():app.dock.show();updateNative();emit('state',snapshot());return snapshot();},
 'save-item':({kind,item})=>{const value=store.upsert(kind,item);if(kind==='expansions')updateNative();emit('state',snapshot());return value;},
 'delete-item':({kind,id})=>{store.remove(kind,id);if(kind==='expansions')updateNative();emit('state',snapshot());return true;},
 'copy':({text})=>{clipboard.writeText(String(text));return true;},
 'paste':({text})=>pasteText(String(text)),
 'paste-last':()=>pasteText(store.data.history.find(x=>x.kind==='dictation')?.text||''),
 'permissions':async()=>{const status=await native.request('status').catch(()=>({}));return{...status,microphone:systemPreferences.getMediaAccessStatus('microphone')==='granted'?3:0};},
 'request-permissions':async({kind})=>{if(kind==='microphone')return{microphone:await systemPreferences.askForMediaAccess('microphone')};return native.request('permissions',{accessibility:kind==='accessibility',screenRecording:kind==='screen'});},
 'open-permissions':({kind})=>shell.openExternal('x-apple.systempreferences:com.apple.preference.security?'+({microphone:'Privacy_Microphone',accessibility:'Privacy_Accessibility',screen:'Privacy_ScreenCapture'}[kind]||'Privacy_Accessibility')),
 'start-recording':({mode='dictation'})=>beginRecording(mode),
 'recording-started':()=>{indicator('recording',activeMode==='note'?'Taking notes':'Listening…');return true;},
 'recording-failed':async({message})=>{if(systemRecording){await native.request('recordSystemStop').catch(()=>{});await fsp.rm(systemRecording,{force:true}).catch(()=>{});systemRecording=null;}recordTarget=null;indicator('idle','');emit('notice',{title:'Recording could not start',body:message});return true;},
 'stop-recording':()=>{emit('recording-control',{action:'stop'});return true;},
 'cancel-recording':async()=>{speech.cancelTranscription();emit('recording-control',{action:'cancel'});if(systemRecording){await native.request('recordSystemStop').catch(()=>{});systemRecording=null;}recordTarget=null;indicator('idle','');return true;},
 'save-recording':async({bytes,mime='audio/webm',mode=activeMode,title,template,personalNotes='',flags=[]})=>{if(!bytes||bytes.byteLength>500e6)throw Error('Recording is too large');const dir=store.data.settings.recordingsDir||path.join(dataDir,'recordings');await fsp.mkdir(dir,{recursive:true});const file=path.join(dir,crypto.randomUUID()+(mime.includes('wav')?'.wav':mime.includes('mp4')?'.m4a':'.webm'));await fsp.writeFile(file,Buffer.from(bytes),{mode:0o600});let input=file;if(systemRecording){const sys=systemRecording;systemRecording=null;await native.request('recordSystemStop');input=await mixAudio(file,sys);}try{return await processFile(input,{kind:mode,title,template,personalNotes,flags});}finally{recordTarget=null;indicator('idle','');}},
 'pause-system-audio':()=>native.request('recordSystemPause'),
 'resume-system-audio':()=>native.request('recordSystemResume'),
 'start-system-audio':async()=>{const file=path.join(dataDir,'recordings',crypto.randomUUID()+'.wav');await fsp.mkdir(path.dirname(file),{recursive:true});await native.request('recordSystemStart',{path:file});systemRecording=file;return true;},
 'choose-files':async()=>{const r=await dialog.showOpenDialog(window,{properties:['openFile','multiSelections'],filters:[{name:'Audio and video',extensions:['wav','mp3','m4a','aac','ogg','flac','wma','opus','mp4','mov','mkv','webm','avi','flv','wmv','mpeg','mpg']}]});r.filePaths.forEach(p=>allowedFiles.add(p));return r.filePaths;},
 'allow-drop':({paths})=>{for(const p of paths){if(typeof p!=='string'||!path.isAbsolute(p)||!fs.existsSync(p))throw Error('Invalid dropped file');allowedFiles.add(p);}return paths;},
 'transcribe-file':async({file,kind='file',template})=>{if(!allowedFiles.has(file))throw Error('Select or drop this file first');return processFile(file,{kind,title:path.basename(file),template});},
 'retry':async({id})=>{const entry=store.data.history.find(e=>e.id===id);if(!entry?.audioPath)throw Error('The audio recording was not retained');return processFile(entry.audioPath,{kind:entry.kind,title:entry.title});},
 'update-history':({id,text})=>{const entry=store.data.history.find(e=>e.id===id);if(!entry)throw Error('Entry not found');entry.text=String(text);store.save();emit('state',snapshot());return entry;},
 'export':async({kind='history',id,format='txt'})=>{const entry=store.data[kind]?.find(e=>e.id===id);if(!entry)throw Error('Entry not found');let content=kind==='notes'?format==='json'?JSON.stringify(entry,null,2):`${entry.summary||''}\n\n## Transcript\n${entry.transcript||''}`:domain.exportTranscript(entry,format);const r=await dialog.showSaveDialog(window,{defaultPath:(entry.title||'Scribble').replace(/[^\p{L}\p{N} ._-]/gu,'')+'.'+format});if(r.canceled)return null;if(format==='pdf'){const{PDFDocument,StandardFonts}=require('pdf-lib');const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);let page=pdf.addPage(),y=790;for(const raw of content.split('\n')){for(let i=0;i<raw.length||i===0;i+=85){if(y<45){page=pdf.addPage();y=790;}page.drawText(raw.slice(i,i+85).replace(/[^\x20-\x7e]/g,'?'),{x:40,y,size:11,font});y-=16;}}await fsp.writeFile(r.filePath,await pdf.save());}else await fsp.writeFile(r.filePath,content);return r.filePath;},
 'import':async({kind})=>{const r=await dialog.showOpenDialog(window,{properties:['openFile'],filters:[{name:'Import',extensions:['json','csv','txt','md']}]});if(r.canceled)return[];const text=await fsp.readFile(r.filePaths[0],'utf8');if(kind==='memory')return store.upsert('memory',{name:path.basename(r.filePaths[0]),content:text.slice(0,50000),enabled:true});const items=domain.parseImport(text,kind);for(const item of items)store.upsert(kind,item);if(kind==='expansions')updateNative();emit('state',snapshot());return items;},
 'backup':async()=>{const r=await dialog.showSaveDialog(window,{defaultPath:'scribble-backup.json'});if(r.canceled)return false;await fsp.writeFile(r.filePath,JSON.stringify(store.data,null,2),{mode:0o600});return r.filePath;},
 'restore':async()=>{const r=await dialog.showOpenDialog(window,{properties:['openFile'],filters:[{name:'Scribble backup',extensions:['json']}]});if(r.canceled)return false;const value=JSON.parse(await fsp.readFile(r.filePaths[0],'utf8'));if(value.version!==1||!value.settings||!Array.isArray(value.history))throw Error('Invalid Scribble backup');await fsp.copyFile(store.file,store.file+'.before-restore-'+Date.now());store.restore(value);updateNative();emit('state',snapshot());return true;},
 'utility':async({operation,options={}})=>{const extensions={'image-convert':options.format||'webp','audio-convert':options.format||'mp3','video-convert':options.format||'mp4','pdf-merge':'pdf','archive-create':'zip','archive-extract':'folder','config-convert':options.format||'json','markdown-pdf':'pdf','text-markdown':'md'};if(!Object.hasOwn(extensions,operation))throw Error('Unknown file operation');const chosen=await dialog.showOpenDialog(window,{properties:operation==='archive-create'?['openFile','openDirectory','multiSelections']:['openFile','multiSelections']});if(chosen.canceled)return null;const destination=await dialog.showSaveDialog(window,{defaultPath:'Scribble-output.'+extensions[operation]});if(destination.canceled)return null;const result=await require('./utilities').performUtility({operation,files:chosen.filePaths,output:destination.filePath,options});return result;},
 'models':()=>speech.listModels(),
 'download-model':async({id})=>{const result=await speech.downloadModel(id);emit('state',snapshot());return result;},
 'cancel-download':({id})=>speech.cancelDownload(id),
 'delete-model':async({id})=>{await speech.deleteModel(id);emit('state',snapshot());return true;},
 'save-api-key':({key})=>{if(!safeStorage.isEncryptionAvailable())throw Error('Secure key storage unavailable');if(key)fs.writeFileSync(path.join(dataDir,'provider.key'),safeStorage.encryptString(String(key)),{mode:0o600});else fs.rmSync(path.join(dataDir,'provider.key'),{force:true});return true;},
 'ai-test':()=>ai.chat(store.data.settings,[{role:'user',content:'Respond with the word ready.'}],apiKey()),
 'ai-models':()=>ai.localModels(store.data.settings),
 'ai-download':()=>ai.pullModel(store.data.settings,x=>emit('ai-download',x)),
 'enhance':({text,instructions})=>enhance(text,{...store.data.settings,aiInstructions:instructions||store.data.settings.aiInstructions}),
 'summarize-note':async({id})=>{const note=store.data.notes.find(n=>n.id===id);if(!note)throw Error('Note not found');let summary;try{summary=await ai.chat(store.data.settings,[{role:'system',content:`Produce precise ${note.template||'meeting'} notes in ${store.data.settings.summaryLanguage}, with overview, actions, decisions. Return Markdown. Do not invent facts.`},{role:'user',content:note.transcript}],apiKey());}catch{summary=ai.extractiveSummary(note.transcript,note.template);}return actions['save-item']({kind:'notes',item:{...note,summary}});},
 'command':async({text,context})=>{const result=await runCommand(String(text),String(context||''));store.addHistory({kind:'command',text:result.text,original:text,command:text,commandResult:result,title:'Command'});emit('state',snapshot());return result;},
 'open-url':({url})=>openUrl(url),
 'open-data':()=>shell.openPath(dataDir),
 'choose-recordings-folder':async()=>{const r=await dialog.showOpenDialog(window,{properties:['openDirectory','createDirectory']});if(r.canceled)return null;await fsp.access(r.filePaths[0],fs.constants.W_OK);return r.filePaths[0];},
 'cancel-timer':({id})=>{clearTimeout(timers.get(id));timers.delete(id);store.data.timers=store.data.timers.filter(t=>t.id!==id);store.save();emit('state',snapshot());return true;},
 'screen-context':async()=>{const sources=await desktopCapturer.getSources({types:['screen'],thumbnailSize:{width:1280,height:720}});return sources.map(s=>({id:s.id,name:s.name,image:s.thumbnail.toDataURL()}));},
 'show':()=>show(),
 'quit':()=>{quitting=true;app.quit();}
};
async function mixAudio(mic,system){const bin=require('./speech').resolveExecutablePath(require('@ffmpeg-installer/ffmpeg').path);const out=path.join(path.dirname(mic),crypto.randomUUID()+'.wav');await new Promise((resolve,reject)=>{const p=spawn(bin,['-y','-i',mic,'-i',system,'-filter_complex','[0:a][1:a]amix=inputs=2:duration=longest:normalize=0','-ac','1','-ar','16000',out]);let err='';p.stderr.on('data',b=>err=(err+b).slice(-3000));p.on('error',reject);p.on('exit',c=>c?reject(Error(err)):resolve());});return out;}
async function dispatch(action,args){if(!Object.hasOwn(actions,action))throw Error('Unknown action');try{return await actions[action](args||{});}catch(e){if(['transcribe-file','retry','save-recording'].includes(action))indicator('idle','');throw e;}}
app.whenReady().then(async()=>{dataDir=process.env.SCRIBBLE_DATA_DIR||path.join(app.getPath('appData'),'Scribble');store=new Store(dataDir);speech=new SpeechEngine({dataDir});native=new NativeBridge(app.isPackaged?path.join(process.resourcesPath,'native/scribble-bridge'):path.join(__dirname,'../../release/native/scribble-bridge'));speech.on('progress',x=>emit('speech-progress',x));speech.on('download-progress',x=>emit('model-download',x));speech.on('models-changed',()=>emit('state',snapshot()));native.on('hotkey',async x=>{if(x.phase==='cancel'){await actions['cancel-recording']({});return;}if(x.mode==='paste-last'&&x.phase==='start'){await actions['paste-last']();return;}if(x.phase==='start')await beginRecording(x.mode);else emit('recording-control',{action:'stop'});});native.on('clipboard',x=>{if(!store.data.settings.clipboardHistory)return;store.data.clipboard.unshift({id:crypto.randomUUID(),text:x.text.slice(0,100000),createdAt:new Date().toISOString()});store.data.clipboard=store.data.clipboard.slice(0,100);store.save();emit('state',snapshot());});
ipcMain.handle('scribble:request',async(event,{action,args})=>{if(![window?.webContents.id,overlay?.webContents.id].includes(event.sender.id))throw Error('Untrusted window');try{return{ok:true,value:await dispatch(action,args)};}catch(e){indicator('idle','');return{ok:false,error:e.message};}});
protocol.handle('scribble-audio',request=>{const id=new URL(request.url).pathname.slice(1);const entry=[...store.data.history,...store.data.notes].find(e=>e.id===id);if(!entry?.audioPath)return new Response('Recording not found',{status:404});return net.fetch(require('node:url').pathToFileURL(entry.audioPath).toString());});

require('electron').session.defaultSession.setPermissionRequestHandler((contents,permission,callback)=>callback(contents===window?.webContents&&['media','audioCapture'].includes(permission)));
for(const t of store.data.timers){timers.set(t.id,setTimeout(()=>{store.data.timers=store.data.timers.filter(x=>x.id!==t.id);store.save();notify('Timer finished',t.title);emit('state',snapshot());},Math.max(0,t.endsAt-Date.now())));}
createWindow();createOverlay();updateNative();if(store.data.settings.startMinimized)window.hide();if(store.data.settings.hideDock)app.dock?.hide();const icon=nativeImage.createFromPath(path.join(__dirname,'../../assets/tray.png'));if(!icon.isEmpty()&&process.platform==='darwin')icon.setTemplateImage(true);tray=new Tray(icon.isEmpty()?nativeImage.createFromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='):icon);tray.setToolTip('Scribble · Speak your mind');tray.setContextMenu(Menu.buildFromTemplate([{label:'Open Scribble',click:show},{label:'Start dictation',click:()=>beginRecording()},{label:'Start a note',click:()=>{show();emit('navigate',{page:'notes',record:true});}},{label:'Paste last dictation',click:()=>actions['paste-last']()},{type:'separator'},{label:'Quit Scribble',click:()=>{quitting=true;app.quit();}}]));tray.on('click',show);
Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'Scribble',submenu:[{role:'about'},{label:'Settings',accelerator:'CmdOrCtrl+,',click:()=>{show();emit('navigate',{page:'settings'});}},{type:'separator'},{role:'hide'},{role:'hideOthers'},{role:'unhide'},{type:'separator'},{role:'quit'}]},{role:'editMenu'},{role:'viewMenu'},{role:'windowMenu'}]));
const socket=path.join(dataDir,'scribble.sock');try{fs.unlinkSync(socket);}catch{}server=http.createServer(async(req,res)=>{let body='';req.on('data',b=>{body+=b;if(body.length>1e6)req.destroy();});req.on('end',async()=>{try{const value=JSON.parse(body||'{}');const permitted=['state','transcribe-file','models','preferences','command','start-recording','cancel-recording','save-item','copy'];if(!permitted.includes(value.action))throw Error('CLI action unavailable');if(value.action==='transcribe-file')allowedFiles.add(value.args.file);const result=await dispatch(value.action,value.args);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,value:result}));}catch(e){res.writeHead(400);res.end(JSON.stringify({ok:false,error:e.message}));}});});server.listen(socket,()=>fs.chmodSync(socket,0o600));
}).catch(e=>{dialog.showErrorBox('Scribble could not start',e.stack||e.message);app.quit();});
app.on('activate',show);app.on('second-instance',show);app.on('before-quit',()=>{quitting=true;native?.close();server?.close();for(const t of timers.values())clearTimeout(t);});app.on('window-all-closed',()=>{});
