'use strict';
const api=window.scribble,$=id=>document.getElementById(id),indicator=$('indicator'),bars=[...$('meter').children];
let locale='en',statusText='',statusKey='overlay.ready';
const t=(key,params)=>ScribbleI18n.t(locale,key,params);
function localizedControls(){document.documentElement.lang=locale;for(const [id,key] of [['open','tray.open'],['start','tray.startDictation'],['stop','overlay.stopRecording'],['cancel','overlay.cancelRecording'],['tone','overlay.chooseTone']]){const el=$(id);el.setAttribute('aria-label',t(key));el.title=t(key);} $('meter').setAttribute('aria-label',t('overlay.microphoneLevel'));$('text').textContent=statusKey?t(statusKey):statusText;}
let phase='idle',style='pill',position='bottom',idleEnabled=false,lastLevel=0,muted=false,tones=[],activeTone='',canSelectTone=false;
const clamp=value=>Number.isFinite(Number(value))?Math.max(0,Math.min(1,Number(value))):0;
function level(rms=0,peak=0){const value=phase==='recording'&&!muted?clamp(rms):0,amplitude=Math.sqrt(value);$('meter').setAttribute('aria-valuenow',String(Math.round(value*100)));$('meter').setAttribute('aria-valuetext',muted?t('state.muted'):t('overlay.level',{level:ScribbleI18n.formatNumber(locale,Math.round(value*100))}));$('meter').classList.toggle('clipped',phase==='recording'&&!muted&&clamp(peak)>=.98);[.4,.65,.85,1,.85,.65,.4].forEach((weight,i)=>bars[i].style.height=(3+Math.round(amplitude*12*weight))+'px');}
function visibility(){indicator.dataset.style=style;indicator.dataset.state=phase;indicator.hidden=style==='hidden'||position==='hidden'||phase==='idle'&&!idleEnabled;$('start').hidden=phase!=='idle';$('stop').hidden=!['recording','paused','starting'].includes(phase);$('cancel').hidden=phase==='idle';$('stop').disabled=phase==='starting';indicator.setAttribute('aria-busy',String(['starting','processing'].includes(phase)));$('tone').hidden=!canSelectTone||!tones.length||phase!=='idle';level();}
function configure(data={}){if(data.locale!==undefined)locale=ScribbleI18n.resolveLocale(data.locale);localizedControls();if(data.selectedTone!==undefined&&data.activeToneId===undefined)data={...data,activeToneId:data.selectedTone};if(data.style!==undefined)style=['pill','notch','hidden'].includes(data.style)?data.style:'pill';if(data.position!==undefined)position=data.position;if(data.idleIndicator!==undefined)idleEnabled=!!data.idleIndicator;if(Array.isArray(data.tones))tones=data.tones;if(data.activeToneId!==undefined)activeTone=data.activeToneId||'';if(data.canSelectTone!==undefined)canSelectTone=data.canSelectTone===true;const chosen=tones.find(tone=>tone&&tone.id===activeTone);$('tone').textContent=(chosen?.name||t('overlay.chooseTone'))+' ▾';$('tone').title=chosen?'Tone: '+chosen.name:t('overlay.chooseTone');visibility();}
async function action(button,command,args){button.disabled=true;try{await api.request(command,args);}catch(error){$('text').textContent=error.message||'Action failed';}finally{button.disabled=false;}}
$('open').onclick=()=>action($('open'),'show');$('start').onclick=()=>action($('start'),'start-recording',{mode:'dictation'});$('stop').onclick=()=>action($('stop'),'stop-recording');$('cancel').onclick=()=>action($('cancel'),'cancel-recording');$('tone').onclick=()=>action($('tone'),'show-tone-menu');
const unsubscribe=api.on(({event,data={}})=>{if(event==='state'){configure({locale:data.settings?.locale,style:data.settings?.indicatorStyle,position:data.settings?.indicatorPosition,idleIndicator:data.settings?.idleIndicator,tones:data.tones,activeToneId:data.activeToneId,selectedTone:data.selectedTone,canSelectTone:data.overlayActions?.includes('show-tone-menu')});}if(event==='overlay-config')configure(data);if(event==='recording-state'){phase=['idle','starting','recording','paused','processing','error'].includes(data.state)?data.state:'idle';muted=!!data.muted;indicator.classList.toggle('muted',muted);statusText=data.text||'';const known={'Ready to listen':'overlay.ready','Starting microphone…':'overlay.starting','Listening…':'overlay.listening','Taking notes':'mode.note','Paused':'state.paused','Microphone muted':'state.muted','Transcribing locally…':'overlay.transcribing','Recording failed':'overlay.failed'};statusKey=data.textKey||known[statusText]||(!statusText?{idle:'overlay.ready',starting:'overlay.starting',recording:data.mode==='note'?'mode.note':'overlay.listening',paused:'state.paused',processing:'overlay.transcribing',error:'overlay.failed'}[phase]:'');configure(data);}if(event==='audio-level'||event==='recording-level'){lastLevel=Date.now();if(data.muted!==undefined){muted=!!data.muted;indicator.classList.toggle('muted',muted);}level(data.rms??data.level,data.peak??0);}});
const staleTimer=setInterval(()=>{if(Date.now()-lastLevel>450)level();},120);
window.addEventListener('pagehide',()=>{clearInterval(staleTimer);unsubscribe?.();});
api.request('state').then(data=>configure({locale:data.settings?.locale,style:data.settings?.indicatorStyle,position:data.settings?.indicatorPosition,idleIndicator:data.settings?.idleIndicator,tones:data.tones,activeToneId:data.activeToneId,selectedTone:data.selectedTone,canSelectTone:data.overlayActions?.includes('show-tone-menu')})).catch(()=>{});visibility();
